apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-ng
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-nginx
  template:
    metadata:
      labels:
        app: test-nginx
    spec:
      containers:
      - name: test-nginx
        image: harbor.dorong9.com/test/nginx:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: default-regcred
---
apiVersion: v1
kind: Service
metadata:
  name: test-nginx
  namespace: default
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: test-nginx