kind: Ingress
metadata:
  namespace: donggu-ns
  name: donggu-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: www.dorong9.com
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: donggu-nginx
              port:
                number: 80