apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: donggu-ingress
  namespace: donggu-1
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    #nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: www.dorong9.com
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: donggu-1-nginx
              port:
                number: 80
    #- host: dorong9.com
    #  http:
    #    paths:
    #    - path: /
    #      pathType: Prefix
    #      backend:
    #        service:
    #          name: donggu-1-nginx
    #          port:
    #           number: 80
    - host: api.dorong9.com
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: donggu-1-tomcat
              port:
                number: 8080