apiVersion: apps/v1
kind: Deployment
metadata:
  name: donggu-1-tomcat
  namespace: donggu-1
spec:
  replicas: 3
  revisionHistoryLimit: 1  # 보관할 ReplicaSet의 수를 3로 제한
  selector:
    matchLabels:
      app: donggu-1-tomcat
  template:
    metadata:
      labels:
        app: donggu-1-tomcat
    spec:
      containers:
      - name: donggu-1-tomcat
        image: harbor.dorong9.com/donggu-private-project-1/back-springtomcat:23
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: donggu-1-regcred
---
apiVersion: v1
kind: Service
metadata:
  name: donggu-1-tomcat
  namespace: donggu-1
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: donggu-1-tomcat