apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: donggu-1-tomcat-hpa
  namespace: donggu-1
spec:
  scaleTargetRef: 
    apiVersion: apps/v1
    kind: Deployment
    name: donggu-1-tomcat
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70