apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: donggu-1-nginx
  namespace: donggu-1
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: donggu-1-nginx
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70