apiVersion: apps/v1
kind: Deployment
metadata:
  name: donggu-1-nginx
  namespace: donggu-1
spec:
  replicas: 3
  revisionHistoryLimit: 1  # 보관할 ReplicaSet의 수를 3로 제한
  selector:
    matchLabels:
      app: donggu-1-nginx
  template:
    metadata:
      labels:
        app: donggu-1-nginx
    spec:
      containers:
      - name: donggu-1-nginx
        image: http://192.168.20.110:8081/donggu-private-project-1/front-react:33
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: donggu-1-regcred
---
apiVersion: v1
kind: Service
metadata:
  name: donggu-1-nginx
  namespace: donggu-1
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: donggu-1-nginx