apiVersion: apps/v1                      # Deployment 리소스의 API 버전
kind: Deployment                         # 리소스 종류 (Deployment)
metadata:
  name: test-nginx                       # Deployment의 이름
spec:
  replicas: 3                            # 생성할 파드(Pod)의 수
    spec:
      containers:                        # 파드에 포함될 컨테이너 정의
      - name: test-nginx                 # 컨테이너의 이름
        image: harbor.dorong9.com/test/nginx:latest  # 컨테이너에서 사용할 이미지
        ports:
        - containerPort: 80              # 컨테이너가 사용하는 포트
      imagePullSecrets:                  # 프라이빗 레지스트리에서 이미지를 가져올 때 사용할 시크릿
      - name: default-regcred             # 시크릿의 이름
---
apiVersion: v1                           # Service 리소스의 API 버전
kind: Service                            # 리소스 종류 (Service)
metadata:
  name: test-nginx                       # Service의 이름
spec:
  ports:
    - protocol: TCP                      # 서비스에서 사용할 프로토콜
      port: 80                           # 서비스가 외부에 노출할 포트
      targetPort: 80                     # 서비스가 트래픽을 전달할 파드의 포트
